from rust:1.61.0
run cargo install wasm-pack
run cargo install cargo-generate
run curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
run apt-get update && apt-get install -y nodejs
run npm install npm@latest -g
run cargo install geckodriver
run apt-get install -y firefox-esr
